name: Deploy Get Images Service To Own Server

on:
  push:
    branches:
      - apis

jobs:
  build:
    steps:
      - name: ssh to servedr
        run: echo ${{ secrets.USERNAME }}@${{ secrets.HOST }}
        run: run ssh ${{ secrets.HOST }}

      - name: Check out repository
        uses: actions/checkout@v2


