name: Trigger Fetch Bing Image App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fetchbingimages" 
          heroku_email: "ligengxin96@gmail.com"
