name: Automated Update README

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: github-update-readme-V2.0
        uses: Ligengxin96/github-update-readme@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          showTrafficData:
            show: true
            position: subhead
          header: About FetchBingDailyImage
          subhead: |
                  The `main` branch project can fetch bing daily image and store in MongoDB.

                  The `apis` branch project can expose the apis so that we can get bing historical daily images.

                  ## How it work

                  Use schedule Github Action to automatically update readme.md file to trigger the Github Action to deploy main branch project to heroku.

                  After deploying in heroku, heroku will automatically execute `npm start` command to run this project, so we can fetch the image everyday.

                  This is like we deploy a azure function in heroku, we can get a free azure function by this way.

                  ## Repo traffic data

                  Total views data: `'{viewsData}'`

                  Total clones data: `'{clonesData}'`

                  ## Latest fetch images time

                  Latest fetch images time: `${{ steps.date.outputs.date }}`

                  ## To everyone

                  If this project is helpful to you please star this project, this is an encouragement to me `:)`
