name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Update README
        uses: theboi/github-update-readme@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          header: "FetchBingDailyImage"
          subhead: Fetch Bing Daily Image and store in mongoose. Latest Fetch Time:${{ steps.date.outputs.date }}